# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
