# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20190801_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_posted',
            new_name='updated_at',
        ),
    ]
